// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from '@prismicio/types';
import type * as prismic from '@prismicio/client';

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Calender documents */
interface CalenderDocumentData {
  /**
   * Calender Title field in *Calender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calender.calender_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  calender_title: prismicT.KeyTextField;
  /**
   * Calender Description field in *Calender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calender.calender_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  calender_description: prismicT.KeyTextField;
  /**
   * Slice Zone field in *Calender*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: calender.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<CalenderDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Calender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calender.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *Calender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calender.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Meta Img field in *Calender*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: calender.meta_img
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_img: prismicT.ImageField<never>;
}
/**
 * Slice for *Calender → Slice Zone*
 *
 */
type CalenderDocumentDataSlicesSlice = DoorSlice;
/**
 * Calender document from Prismic
 *
 * - **API ID**: `calender`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalenderDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
  Simplify<CalenderDocumentData>,
  'calender',
  Lang
>;
export type AllDocumentTypes = CalenderDocument;
/**
 * Item in Door → Items
 *
 */
export interface DoorSliceDefaultItem {
  /**
   * Door Img field in *Door → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: door.items[].door_img
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  door_img: prismicT.ImageField<never>;
  /**
   * Door Number field in *Door → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: door.items[].door_number
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  door_number: prismicT.NumberField;
  /**
   * Door Text field in *Door → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: door.items[].door_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  door_text: prismicT.KeyTextField;
}
/**
 * Default variation for Door Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Door`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DoorSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<DoorSliceDefaultItem>
>;
/**
 * Slice variation for *Door*
 *
 */
type DoorSliceVariation = DoorSliceDefault;
/**
 * Door Shared Slice
 *
 * - **API ID**: `door`
 * - **Description**: `Door`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DoorSlice = prismicT.SharedSlice<'door', DoorSliceVariation>;
declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      CalenderDocumentData,
      CalenderDocumentDataSlicesSlice,
      CalenderDocument,
      AllDocumentTypes,
      DoorSliceDefaultItem,
      DoorSliceDefault,
      DoorSliceVariation,
      DoorSlice,
    };
  }
}
